### ISSUE TITLE
you didnt import speed

### ISSUE THREAD

**Issue by sargon64** [innacc/AutoSporkLoginForLinux#1]
make sure to
`import speed`

btw can i fork this project?

**Comment by sargon64** [comment]
darn it ima just fork it anyhow

**Comment by innacc** [comment]
yes you can fork it. The program no longer works because the website was redesigned. I have an updated version for Linux that does work but I haven't uploaded it yet. would you like to have it

**Comment by innacc** [comment]
all you have to do is replace the join button line with join_button = driver.find_element_by_css_selector(".sign")

**Comment by sargon64** [comment]
I'm actually going to do a rewrite in C++. If you would like to help you can contact me on discord  with "Sargon64#9999" without the quotes.,
